#!/bin/bash

(
    set -e

    cd ..
    git pull --rebase

    # Install new modules if they were added
    npm install

    kill $(cat nodepid) || true

    nohup node Server.js &
    echo $! > nodepid
) &>> update_and_restart_log &

exit
